version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspace
    command: sleep infinity
    environment:
      - NODE_ENV=development
    networks:
      - dev-network
    depends_on:
      - supabase
      - ollama

  # Supabase services
  supabase:
    image: supabase/cli:latest
    volumes:
      - ./supabase:/app/supabase:cached
      - supabase_data:/var/lib/postgresql/data
    ports:
      - "54321:54321"  # Studio
      - "54322:54322"  # Database
      - "54323:54323"  # REST API
      - "54324:54324"  # Auth
      - "54325:54325"  # Storage
      - "54326:54326"  # Edge Functions
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - dev-network
    command: ["sh", "-c", "supabase start --ignore-health-check || tail -f /dev/null"]

  # Ollama service for AI
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - dev-network
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["ollama", "serve"]

  # PostgreSQL for Supabase (if needed separately)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-network

volumes:
  supabase_data:
  ollama_data:
  postgres_data:

networks:
  dev-network:
    driver: bridge
